name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./EraZor.sln

      # Build project
      - name: Build project
        run: dotnet build ./EraZor.sln --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      - name: Run Unit Tests
        run: dotnet test EraZor.Tests/EraZor.Tests.csproj --filter Category=Unit --configuration Release

      - name: Run Integration Tests
        run: dotnet test EraZor.Tests/EraZor.Tests.csproj --filter Category=Integration --configuration Release

  e2e:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run E2E Tests
        run: newman run ./EraZor.postman_collection.json

  deploy:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy with Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d --build
